### ISSUE TITLE
JS-Error in Chrome

### ISSUE THREAD

**Issue by wgruenberger** [FriendsOfREDAXO/video#15]
Seit kurzem (der neuen Chrome-Version) funktioniert auf unserer Seite im Chrome der Afterglow-Player nicht mehr (scrollen zu "Film ansehen"):
https://www.netfiles.de/

`afterglow.min.js:18 Uncaught TypeError: Cannot read property 'vdata1547733945317' of null`

In Firefox und IE gehts. Ist das Problem woanders auch bereits aufgetreten oder liegts an unserer Konfiguration?

**Comment by skerbis** [comment]
Ich kann das Problem reproduzieren bestätigen.

**Comment by wgruenberger** [comment]
PLYR wollten wir nicht verwenden, da wir das Video erstmal nur als Link anzeigen wollen.
Nur zu meinem Verständnis - du konntest das Problem auf einer anderen Seite reproduzieren?

**Comment by skerbis** [comment]
hmm .. nein bei Dir. Tatsächlich läuft es auf anderen Seiten. 
Ich schätze es ist doch ein Problem auf der Seite selbst. Schau mal das Original auf der Website unten: 
https://afterglowplayer.com
