### ISSUE TITLE
Autoplay Einstellung nicht korrekt bei afterglow Modul Beispiel

### ISSUE THREAD

**Issue by godsdog** [FriendsOfREDAXO/video#16]
Wenn man den Afterglow Player nutzt und unter den Einstellungen Autoplay auf "Nein" stellt wird im Beispielmodul `autoplay=""` ausgegeben. Damit startet der Player automatisch.

Ich habe es so umgemodelt:

`
if($afterglow->checkMedia($file) !== false) {
$aplay = '';
if ($autoplay != "") $aplay = 'autoplay="'.$autoplay.'" ';
    echo '
        <video '.$aplay.'data-volume="'.$sounds.'" data-skin="'.$theme.'" class="afterglow" id="myvideo" width="1080" height="720">
            <source type="video/mp4" src="'.$link.'" />
        </video>
        ';
}`

**Comment by skerbis** [comment]
Danke. Ist nun so übernommen.
