### ISSUE TITLE
Hilfe - Einbindung "plyr_video.js" im Frontend

### ISSUE THREAD

**Issue by greatif** [FriendsOfREDAXO/video#5]
Pfad ist dort aktuell (Ver. 1.2.0) angegeben mit `assets/addons/video/Plyr/js/plyr_video.js`.
Datei befindet sich tatsächlich in `/assets/addons/video/js/plyr_video.js`

**Comment by skerbis** [comment]
Ist gefixt. Ist bereits im Installer aktualisiert. (keine neue Version)
